import React from "react";
import './MathKeyboard.css';

const MathKeyboard = () => {

    return (
      <div className={'keyboard'}>
          <div>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
          </div>
          <div>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
          </div>
          <div>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
          </div>
          <div>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
          </div>
          <div>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
              <button>
                  hello
              </button>
          </div>
      </div>
    );
}

export default MathKeyboard;